### ISSUE TITLE
HTTP.select().flatten() make requests fire twice

### ISSUE THREAD

**Issue by Hypnosphi** [cyclejs/cyclejs#503] opened 2016-12-31 14:59 UTC
**Code to reproduce the issue:**
https://esnextb.in/?gist=0765658af0d20a82ff8486df4cdab607

**Expected behavior:**
Each request is fired once

**Actual behavior:**
Each request is fired twice

**Versions of packages used:**
latest xstream, @cycle/xstream-run, @cycle/http

Looks like this is because of Map+Flatten fusion where Map is inside the driver (and is responsible for http side-effects), and Flatten inside the app

**Comment by Hypnosphi** [comment] 2016-12-31 15:48
Maybe the stream adapters should always apply a dummy `.filter(() => true)` to prevent such fusions between app and driver operators

**Comment by staltz** [comment] 2017-01-13 09:46
Thanks for the reproducing example. If we cannot find a solution to this fusion-related bug in xstream, we'll remove fusion, because there's no point in adding `.debug(() => {})`. The whole point of fusion is to remove one operator from the operator chain. Adding one back makes it `-1+1==0`.

Thoughts @TylorS ?

**Comment by Hypnosphi** [comment] 2017-01-13 10:30
Well, the conjunction of app and driver code is quite a specific place, the fusion may still be helpful in othersSent from Yandex.Mail for mobile: http://m.ya.ru/ymail13.01.2017, 09:46, "André Staltz" <notifications@github.com>:Thanks for the reproducing example. If we cannot find a solution to this fusion-related bug in xstream, we'll remove fusion, because there's no point in adding .debug(() => {}). The whole point of fusion is to remove one operator from the operator chain. Adding one back makes it -1+1==0.
Thoughts @TylorS ?

**Comment by staltz** [comment] 2017-03-24 13:37
This bug still happens with the latest versions of the packages.

**Comment by staltz** [comment] 2017-03-24 13:52
To document my discoveries (I'll do the fix later):

The dataflow looks like 

1. requestSink$ from the app
2. requestSinkProxy$ in run, this is MemoryStream
3. map(requestInputToResponse$) in HTTP driver
4A. subscribe to this above in the HTTP driver in eager (default) mode
4B. (Continuing from step 3) flatten() in the app
5. The stream from 4B is used in the app and somewhere down the chain there is a subscription

The map+flatten fusion from 4B will cause the map(requestInputToResponse$) to happen again, which will cause a second undesired side effect, after it has been caused by 4A.

Possible solutions:
- Remove map+flatten fusion from xstream
- Put a dummy operator in between map and flatten as a hack to bypass the fusion
- Make an explicit `.noFusion()` operator in xstream for these purposes
- In xstream, avoid map+flatten fusion if the map stream already has some listeners
- Any other idea someone else suggests

**Comment by Hypnosphi** [comment] 2017-03-24 14:00
>In xstream, avoid map+flatten fusion if the map stream already has some listeners

That's my favourite

**Comment by whitecolor** [comment] 2017-03-24 15:34
What is meant by "fusion"?

**Comment by Hypnosphi** [comment] 2017-03-24 15:46
When you do `stream.map(...).flatten()`, xstream uses a single MapFlatten operator for that

**Comment by whitecolor** [comment] 2017-03-24 16:10
@staltz how the first and the fourth options will effect xstream work what are the consequences for users?

**Comment by staltz** [comment] 2017-03-24 17:12
> What is meant by "fusion"?

https://github.com/staltz/xstream/blob/master/src/index.ts#L1895

> how the first and the fourth options will effect xstream work what are the consequences for users?

There would be less bugs. I really doubt that people would depend on this behavior, but it would be anyway a breaking change according to ComVer.

**Comment by staltz** [comment] 2017-04-03 14:32
This is now fixed in xstream v10.4 https://www.webpackbin.com/bins/-KgoDZWYbGQ3WRavJLKo

**Closed by staltz** 2017-04-03 14:32 UTC
Labels: issue is bug, priority 3 (should), scope: misc
