### ISSUE TITLE
HTTP driver erroneously replays previous request

### ISSUE THREAD

**Issue by ntilwalli** [cyclejs/cyclejs#592] opened 2017-04-27 21:17 UTC
While updating to Cycle Unified I noticed that some of my HTTP requests from a previous component are being replayed when a new component gets swapped in.  I traced the issue to `makeSinkProxies` which is improperly defaulting all proxies to `MemoryStream`. Not all sinks should be represented using MemoryStream, the HTTP stream being a clear example.

https://github.com/cyclejs/cyclejs/blob/69f932ca01abafad8b08d111c0d639cb9b013f8b/run/src/index.ts#L83

```js
function makeSinkProxies<So extends Sources, Si extends Sinks>(
                        drivers: Drivers<So, Si>): SinkProxies<Si> {
  const sinkProxies: SinkProxies<Si> = {} as SinkProxies<Si>;
  for (const name in drivers) {
    if (drivers.hasOwnProperty(name)) {
      sinkProxies[name] = xs.createWithMemory<any>();  // <-------- THIS IS WRONG FOR HTTP
    }
  }
  return sinkProxies;
}
```

**Comment by staltz** [comment] 2017-04-28 08:05
Okay, this is a nasty problem.

I remember reverting to normal Stream, then other issues started popping up, and we used MemoryStream, I even left a comment behind so we would remember exactly why is it a memory stream: https://github.com/cyclejs/cyclejs/blob/69f932ca01abafad8b08d111c0d639cb9b013f8b/run/src/index.ts#L44-L58

```js
/**
 * Sink proxies should be MemoryStreams in order to fix race conditions for
 * drivers that subscribe to sink proxies "later".
 *
 * Recall that there are two steps:
 * 1. Setup (sink proxies -> drivers -> sources -> main -> sink)
 * 2. Execution (also known as replication: sink proxies imitate sinks)
 *
 * If a driver does not synchronously/immediately subscribe to the sink proxy
 * in step (1), but instead does that later, if step (2) feeds a value from the
 * sink to the sink proxy, then when the driver subscribes to the sink proxy,
 * it should receive that value. This is why we need MemoryStreams, not just
 * Streams. Note: Cycle DOM driver is an example of such case, since it waits
 * for 'readystatechange'.
 */
```

I'm not sure what would be the solution. Maybe `UglyFixStream extends Stream` where UglyFixStream replays the remembered value just once, then from that moment onwards behaves like a Stream.

**Comment by ntilwalli** [comment] 2017-04-28 12:21
Replaying only the first emission will not fix the problem. 

If a component gets swapped in using `map + flatten` during app execution, then it's initial wiring could happen well after the initial wiring during `run`, and if that component sends an immediate HTTP request and the response stream has not been subscribed/wired-into-the-component yet (due to ordering) then it will be dropped.  I've personally handled this issue at the app-level by delaying all HTTP requests by the min amount to ensure they get sent after full wiring... there may be a better solution.

**Comment by ntilwalli** [comment] 2017-04-28 12:24
Delaying all requests in the HTTP driver would fix the issue, but may be too heavy-handed.

**Comment by staltz** [comment] 2017-04-28 12:28
I don't see a problem if all requests in the HTTP driver are async but asap, using e.g. Promise resolve lifecycle, which is sooner than setTimeout.

**Comment by ntilwalli** [comment] 2017-04-28 12:31
I've also applied the same delay approach to my `Router` sink (I use cyclic-router) since I sometimes want to redirect the app away from the requested page immediately and this sink could receive an emission before full wiring.  In this case the delay fix works, but I guess the remember-only-the-first-emission-UglyFixStream approach would also work since the delay is only needed during initial `run`-wiring.

**Comment by ntilwalli** [comment] 2017-04-28 12:38
Using a promise seems like a good solution, but it's driver-land.  Do you think managing this issue is a driver-writer's responsibility?

**Comment by staltz** [comment] 2017-05-05 08:32
> but I guess the remember-only-the-first-emission-UglyFixStream approach would also work since the delay is only needed during initial run-wiring.

If this actually fixes this issue, I would prefer it, because the issue is actually related to "running main and drivers and plugging them together" which is a cycle/run concern, and also having this fix in cycle/run would simplify driver code. If that solution doesn't fix it, I'm fine with having the solution in driver-land.

**Comment by ntilwalli** [comment] 2017-05-05 13:16
The "remember-only-the-first-emission-UglyFixStream approach" would only fix my Router issue, it would not fix the HTTP issue.  

Just to be clear, you agree then with the ideas`delay(1)` is the generally accepted approach for dealing with sinks that could emit before all sources/sinks are wired up (regardless of whether the wiring happens during `run` or during a `map + flatten`), yes?

If this is a driver-land concern then do you agree the MemoryStream default for sinks should be changed back to Stream in `@cycle/run`?

**Comment by staltz** [comment] 2017-05-05 14:39
Hmm I thought the FixStream would fix your HTTP issue. Anyway I think we can't do the driver-land idea in general because MemoryStream proxy sinks in cycle/run are required to fix a bug with Cycle DOM. I'm okay with any solution that works to fix this HTTP issue, as long as we don't unfix other bugs.

**Comment by ntilwalli** [comment] 2017-05-05 15:20
Would it be okay to add an argument to run which allows you to flag which sinks you want to proxy with a regular Stream instead of a MemoryStream?

**Comment by jvanbruegge** [comment] 2017-05-05 15:57
I would let the drivers announce this themselves, so I (as a user) don't have to worry about that. The DOM driver could request a MemoryStream Proxy, while the HTTP driver could not

**Comment by whitecolor** [comment] 2017-05-06 12:12
What if be just replace `MemoryStream` with `Stream`?

**Comment by staltz** [comment] 2017-05-10 12:54
> Would it be okay to add an argument to run which allows you to flag which sinks you want to proxy with a regular Stream instead of a MemoryStream?

Changing the API should be our last choice, even if it's not a breaking change. Can't this be fixed without changing the API?

> What if be just replace MemoryStream with Stream?

Then tests won't pass. See my first comment in this thread.

**Comment by whitecolor** [comment] 2017-05-10 15:42
@staltz only one test `should support driver that asynchronously subscribes to sink` doesn't pass

And are you sure that is should pass? I think this test is invalid. 

https://github.com/cyclejs/cyclejs/blob/master/run/test/index.ts#L390

Memory stream in this case that keeps only one value can ensure that late subscriber will get only one last value, that is all. And if you want support such drivers cycle should hold the buffer in sink before it is subscribed like [it does here](https://github.com/cyclejs/cyclejs/blob/master/run/src/index.ts#L162) 

Btw it relates somehow to signals thing, when consumer is responsible for getting events.

**Comment by ntilwalli** [comment] 2017-05-11 05:46
It does seem like certain sinks represent a value-over-time (DOM) and other represent events (HTTP) and the proxy (Stream vs MemoryStream) which is used should be configurable.  I don't know the best way to accomplish that configurability, but the distinction seems important.

**Comment by whitecolor** [comment] 2017-05-11 15:42
I think currently sinks should be Streams only (not MemoryStreams). And driver should be responsible for backpressure and late subscription, probably Signal proposal will fix this. So DOM driver should be modified to handle this stream.

**Comment by staltz** [comment] 2017-05-12 14:43
@whitecolor 

> only one test `should support driver that asynchronously subscribes to sink` doesn't pass
> And are you sure that is should pass? I think this test (and maybe the case) is invalid.

This test is essential, and I said before that it's the case of the DOM Driver. It subscribes only when the DOM is in `readystate`, which can happen asynchronously.

@ntilwalli 
> It does seem like certain sinks represent a value-over-time (DOM) and other represent events (HTTP) and the proxy (Stream vs MemoryStream) which is used should be configurable. I don't know the best way to accomplish that configurability, but the distinction seems important.

This is a really good point, thanks Nikhil! I think we can leverage to take a step forward towards the solution. That gave me the idea of checking what is the type of the sink, whether it's Stream or MemoryStream, but then again, drivers only get sink proxies, and these are all of the same type. Maybe we can do this "instance of" verification when we replicate sink with sink proxies (`replicateMany`), but that may not solve the problem. Or does it?

> The "remember-only-the-first-emission-UglyFixStream approach" would only fix my Router issue, it would not fix the HTTP issue.

Can you elaborate a bit more on why it wouldn't work? I can't see the reason.

> I think currently sinks should be Streams only (not MemoryStreams). And driver should be responsible for backpressure and late subscription, probably Signal proposal will fix this. So DOM driver should be modified to handle this stream.

Yeah, I can see how Signal would probably touch on this issue significantly.

**Comment by jvanbruegge** [comment] 2017-05-12 15:47
> Maybe we can do this "instance of" verification when we replicate sink with sink proxies (replicateMany), but that may not solve the problem. Or does it?

As said, I would move this decision to the driver, by introducing a getter or something like `isolateXXX`

**Comment by staltz** [comment] 2017-05-12 16:22
@jvanbruegge how would this actually look like? 

> I would let the drivers announce this themselves, so I (as a user) don't have to worry about that. The DOM driver could request a MemoryStream Proxy

Drivers get a proxy stream as function input, so I'm not sure what "request" or "announce" would look like. Can you elaborate?

**Comment by jvanbruegge** [comment] 2017-05-12 16:34
AFAIK, not all drivers need a proxied stream. Only the DOM driver, because he subscribes asynchronously. So the driver could have a function `createProxy` that instanciates a Proxy stream. For all drivers not having the function it is just `identity`

**Comment by whitecolor** [comment] 2017-05-12 16:42
> As said, I would move this decision to the driver, 

This would complicate cycle run architecture.

> This test is essential, and I said before that it's the case of the DOM Driver. It subscribes only when the DOM is in readystate, which can happen asynchronously.

I understand this. I say driver itself could handle this. This would unify and simplify run stream architecture. In future you probably would use signal not stream for such things.

In DOM could be done something like this, get remembered behaviour:
```ts
vnode$ = vnode$.remember()
....
if (document.readyState === 'loading') {
  const emtyListener = {}
  vnode$.addListener(emtyListener)
   document.addEventListener('readystatechange', () => {
     if (document.readyState === 'interactive') {
       vnode$.removeListener(emptyListener)
       rootElement$.addListener(listener);
     }
  });
...
```

**Comment by ntilwalli** [comment] 2017-05-12 20:16
> The "remember-only-the-first-emission-UglyFixStream approach" would only fix my Router issue, > it would not fix the HTTP issue.

> *Can you elaborate a bit more on why it wouldn't work? I can't see the reason.*

I use `map + flatten` extensively in my code for instantiating components.  That means my stream pipeline is not static, it changes dynamically all the time.  Certain components that I swap in need to send an HTTP request immediately upon being swapped in.  Without a delay added to the HTTP sink for that component, the response may get received before the HTTP source for the component is wired into the app, effectively dropping the response which was destined for that component.  Buffering one emission once during startup does not solve this wiring-order issue for this type of component.

In the case of the Router sink the only time I've ever needed to re-route immediately (emit something on the Router sink upon component initialization) is on top-level app initialization (due to the user not having access to the requested route), thus doing the buffer-one-emission-only at startup would work in my case for the Router.

**Comment by staltz** [comment] 2017-07-13 21:07
I got a reproduction case:

```js
import xs from 'xstream';
import {run} from '@cycle/run';
import {div, h1, makeDOMDriver} from '@cycle/dom';
import {makeHTTPDriver} from '@cycle/http';
import {timeDriver} from '@cycle/time';

function child(sources, num) {
  const vdom$ = sources.HTTP.select('cat')
    .flatten()
    .map(res => res.body.name)
    .map(name =>
      div([
        h1('My name is ' + name)
      ])
    );

  const request$ = num === 1 ? xs.of({
    category: 'cat',
    url: 'http://jsonplaceholder.typicode.com/users/1'
  }) : xs.never();

  return {
    HTTP: request$,
    DOM: vdom$,
  };
}

function main(sources) {
  const sinks$ = sources.Time.periodic(500).take(6).map(i => {
    if (i % 2 === 1) {
      return child(sources, i);
    } else {
      return {
        HTTP: xs.empty(),
        DOM: xs.of(div()),
      }
    }
  });

  // order of sinks is important to reproduce the bug
  return {
    HTTP: sinks$.map(sinks => sinks.HTTP).flatten(),
    DOM: sinks$.map(sinks => sinks.DOM).flatten(),
  }
}

run(main, {
  DOM: makeDOMDriver('#main-container'),
  HTTP: makeHTTPDriver(),
  Time: timeDriver
});
```

- - -

The good news is that I have accepted the idea of drivers being able to flag what kind of sink does it expect, with `driverFunction.needsMemorySink = true` (while by default other driver functions can specify false or not specify this property, so it's undefined, hence falsy), and so the DOM driver is an odd case and would be the only one I know which would specify that flag.

The bad news is that such flag is not enough to solve the bug. The reproduction case above happens even if all sink proxies are (non-Memory) streams.

It seems like we may need to force the HTTP driver to delay every request a bit. At least I haven't found another solution to the reproduction case above.

A drill-down how the bug actually occurs:

1. when `i = 1`, the main's HTTP sink subscribes to the child's HTTP sink
2. the child HTTP sink synchronously emits
3. the HTTP driver sees that request and with eager mode as default, will send out the request asap
4. at this point, no other subscriber is interested in the request, except the dummy subscriber inside HTTP driver
5. (all the above happened synchronously, this is why:) the main's DOM sink subscribes to the child's DOM sink
6. the child's vdom$ subscribes to the response$$
7. nothing will happen on response$$ from now onwards, because response$$ emits synchronously with request$ (the HTTP sink)
8. nothing is shown on the DOM

**Comment by staltz** [comment] 2017-07-13 21:15
I'm trying to make this a cycle/run bug and therefore a cycle/run fix. I'd like to achieve this guarantee: the source event corresponding to a sink event should never be happen in the same event loop. Is this reasonable?

**Comment by staltz** [comment] 2017-07-13 21:29
I'm starting to think this the suggestion above would be reasonable. We basically just need `sinkProxy -> sink` replication to be async, with e.g. `setImmediate`:

```diff
  sinkNames.forEach(name => {
    const listener = sinkProxies[name];
    const next = (x: any) => {
-     listener._n(x);
+     setImmediate(() => listener._n(x));
    };
    const error = (err: any) => {
+     setImmediate(() => {
        logToConsoleError(err);
        listener._e(err);
+     });
    };
    buffers[name]._n.forEach(next);
    buffers[name]._e.forEach(error);
    replicators[name].next = next;
    replicators[name].error = error;
    // because sink.subscribe(replicator) had mutated replicator to add
    // _n, _e, _c, we must also update these:
    replicators[name]._n = next;
    replicators[name]._e = error;
  });
```

Relevant background on synchronous execution: https://github.com/cyclejs/cyclejs/issues/200

But that issue was about "we want to grab sources and sinks synchronously before main and drivers are connected" and we can still support that while having my suggestion implemented.

**Comment by ntilwalli** [comment] 2017-07-13 21:32
Looks like a reasonable fix to me. It would be odd if anyone relied on synchronous message passing between a sink and source.

**Comment by whitecolor** [comment] 2017-07-14 14:36
Should be careful with async, and instead of `setImmidiate` maybe better to use with `Promise.resolve(x).then((x) => )` here.

**Comment by staltz** [comment] 2017-07-19 12:35
Okay, I think the setImmediate solution will be my plan A to solve this issue.
@whitecolor what risks do you think there are associated with setImmediate? I would use the polyfill https://github.com/YuzuJS/setImmediate which is heavily tested and supports all sorts of browsers, while native Promise is not everywhere.

**Comment by TylorS** [comment] 2017-07-19 13:37
The only thing about `setImmediate` I'd bring up is it is a non-standard with no intentions of becoming a standard. And the only browsers that support the API is Internet Explorer and Edge.

http://caniuse.com/#feat=setimmediate
https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate

**Comment by staltz** [comment] 2017-07-19 14:00
That's a good point to note. I'm not so worried about it, but I am a bit worried about the polyfill's size. It's not big, but it's not tiny either.

**Comment by TylorS** [comment] 2017-07-19 14:22
Personally I think making use of `Promise` to be a good solution as @whitecolor mentioned. 
All supported browsers (by browser vendors) support `Promise`. For developers who must support browsers that do not have native promises can choose from a large range of polyfills ranging from [small](https://github.com/lahmatiy/es6-promise-polyfill/blob/master/promise.min.js) to something larger like [bluebird](https://github.com/petkaantonov/bluebird) or [creed](https://github.com/briancavalier/creed) which are much faster than native promises and offer more features that can be beneficial to the project in other ways.

**Comment by staltz** [comment] 2017-07-20 17:38
Yeah, that's a good point. I'm not sure what to do here, because IE10 and IE11 are still globally used quite a lot (more than Safari), so for many projects we'd have to inform developers to remember to polyfill Promise, whereas before this wasn't necessary. We'll have to do that actually for cycle/dom tests in order to pass saucelabs.

On one hand we could just always ship the Promise polyfill (and try to make that small), on the other hand I'm a bit worried about adding a noticeable delay to all sink emissions, so it's important that this sink delay proposal is the smallest delay possible. Like, if the Promise polyfill for IE uses setTimeout, then we're basically adding a global delay to all events for users of that browser.

Maybe another solution is to check for Promise existence, and if not, then not delay, which would preserve this buggy behavior for IE browsers. Not fixing this bug for all browsers sounds odd, but anyway we would have to notify IE developers to do something, **OR** put a burden on all browser users by shipping the Promise polyfill.

I'll experiment a bit with these ideas.

**Comment by TylorS** [comment] 2017-07-20 21:14
Maybe just a small function like this?

```
const runOnNextTick = f=> typeof Promise !== 'undefined'
  ? Promise.resolve(f).then(g => g())
  : setTimeout(f, 0)
```

**Comment by whitecolor** [comment] 2017-07-21 12:19
Not to do checks on each `next`:
```ts
const runOnNextTick = typeof Promise !== 'undefined'
  ? (f) => Promise.resolve().then(() => f())
  : typeof setImmediate !== 'undefined' 
    ? (f) => setImmediate(f) : (f) => setTimeout(f, 0)
```

**Comment by fuunnx** [comment] 2017-07-21 16:04
I just want out point out that I can see one small (but major ?) issue to delay using setTimeout, and it is when the user executes some code that requires to be run during the *current* tick (like a 'preventDefault' driver).

However the Promise trick (without swallowing errors ^^) is working well in that situation (thanks [microTasks](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/)). 
Also have a look at DOMMutationObserver which has a [wider browser support](http://caniuse.com/#feat=mutationobserver).

I did some tests (only on Chrome, not IE ^^):
```html
Right click on an element. If should NOT display the contextMenu. If it does, preventDefault failed.

<button class="sync">sync prevented</button>
<button class="setTimeout">setTimeout prevented</button>
<button class="promise">Promise prevented</button><!-- uses DOM mutation observer -->
<button class="asap">asap prevented</button><!-- uses DOM mutation observer -->
<button class="animationFrame">animationFrame prevented</button>
<button class="setImmediate">setImmediate prevented</button>
```

```js
import asap from 'asap'
import immediate from 'immediate'


document.querySelector('.sync').addEventListener('contextmenu', ev => {
  ev.preventDefault() // prevented
})

document.querySelector('.setTimeout').addEventListener('contextmenu', ev => {
  setTimeout(() => ev.preventDefault(), 0) // NOT prevented
})

document.querySelector('.promise').addEventListener('contextmenu', ev => {
  Promise.resolve().then(() => ev.preventDefault()).catch(e => {throw e}) // prevented
})

document.querySelector('.asap').addEventListener('contextmenu', ev => {
  asap(() => ev.preventDefault()) // (uses DOM mutation observer), prevented
})

document.querySelector('.immediate').addEventListener('contextmenu', ev => {
  immediate(() => ev.preventDefault()) // (uses DOM mutation observer), prevented
})

document.querySelector('.animationFrame').addEventListener('contextmenu', ev => {
  requestAnimationFrame(() => ev.preventDefault())  // NOT prevented
})

document.querySelector('.setImmediate').addEventListener('contextmenu', ev => {
  setImmediate(() => ev.preventDefault())  // NOT prevented
})
```

If a Promise polyfill is needed, I suggest using some "microScheduler" library like [immediate](https://github.com/calvinmetcalf/immediate) or [asap](https://github.com/kriskowal/asap) instead, which seem to have a good browser support (did not test by myself) and are often used under the hood of those Promise polyfills. But I'm afraid they still fallback to setTimeout which would break in this particular use case.

**Comment by ntilwalli** [comment] 2017-07-21 16:58
@fuunnx This discussion is about source-emissions.  A `preventDefault`-driver is read-only and I don't believe this discussion applies to read-only drivers (it reads from a sink and doesn't emit on a source, i.e. it takes an event coming from the sink, applies `preventDefault` to it (synchronously) and is done.)  Only emissions that happen on a source stream as a result of what comes in on a sink stream would have this async boundary introduced.

**Comment by staltz** [comment] 2017-07-31 19:30
The setImmediate (or runOnNextTick) solution would break [a test that checks that `run` is synchronous](https://github.com/cyclejs/cyclejs/blob/506bf88a7e99778b72ba500ea2d8bf70599a2620/run/test/index.ts#L356-L383), which lead me to dig up what was that test for, and it brought up an [old issue](https://github.com/cyclejs/cyclejs/issues/200) and an [old discussion](https://gitter.im/cyclejs/cyclejs?at=569934f75de13b3f15e34af6) that @laszlokorte and @whitecolor started, and I have to agree with important statements they made:

> It should be possible to reduce the 1ms timeout to 0ms

> Is a generic problem of using setTimeout. You can relax browser using it or wait (ensure) something to happen in synchronious stream, but you get operation slowed down due to it wait sync actions to complete before go to next tick

So I made a different solution, which is PR https://github.com/cyclejs/cyclejs/pull/658:

- No more MemoryStreams as sink proxies in`run`
- Cycle HTTP uses a custom buffer approach
- Cycle DOM uses a custom buffer approach

MemoryStream sinks affect app behavior too intrusively, so the buffer approach in drivers is meant to solve the synchronous race condition and only that, not affecting app behavior.

Also the setImmediate approach for all sink emissions would be too intrusive, it would literally delay everything in all apps. 

Does the PR look good?

**Comment by whitecolor** [comment] 2017-08-01 05:04
> MemoryStream sinks affect app behavior too intrusively, so the buffer approach in drivers is meant to solve the synchronous race condition and only that, not affecting app behavior.

Yes [I noticed this in my first comment](https://github.com/cyclejs/cyclejs/issues/592#issuecomment-300830258), this would be probably the best generic solution to the problem.

**Comment by whitecolor** [comment] 2017-08-04 18:33
@staltz 
Due to this change `response$$` no more will be `MemoryStream` (which is actually a good thing).
```
const response$$ = request$.map(requestInputToResponse$);
```

This is one of the breaking changes. Do you consider it?

**Comment by staltz** [comment] 2017-08-07 21:58
@whitecolor I didn't understand, sorry, what is the breaking change?

**Comment by whitecolor** [comment] 2017-08-08 06:16
@staltzI I mean that currently as request$ sink is MemoryStream, then HTTP source response$$ is too MemoryStream. And after PR it will be just a Stream, not remembered. This relates to the issues arisen in my comments to PR, let's discuss it there.

**Closed** 2017-11-10 08:33 UTC
Labels: issue is bug, priority 4 (must), scope: http, scope: run

**Comment by staltz** [comment] 2017-11-10 08:35
New versions of cycle/run and cycle/dom will come out for this issue, soon
