### ISSUE TITLE
Rendering the same content on both server and client causes a loss of events

### ISSUE THREAD

**Issue by krainboltgreene** [cyclejs/cyclejs#750] opened 2017-11-27 02:19 UTC
**Code to reproduce the issue:**

https://github.com/krainboltgreene/deushack

**Expected behavior:**

If I click on an element I should receive a click event.

**Actual behavior:**

Nothing happens

**Versions of packages used:**

Latest

**Comment by krainboltgreene** [comment] 2017-11-27 02:26
I'm able to hack around this by either rendering something different after client side has booted. For example, if I add a `data-created-at=new Date()` to a dom tree element I suddenly get my events.

I'm guessing this is as much snabbdom as cycle/dom?

**Comment by staltz** [comment] 2017-11-27 11:45
Hi @krainboltgreene 
Thanks for letting us know about this.
I think I can reproduce this by updating libraries in examples/advanced/isomorphic and not having click events preventDefault'd on client side.

**Comment by krainboltgreene** [comment] 2017-11-27 18:19
Let me know if I can help with this at all.

**Comment by staltz** [comment] 2017-11-27 21:21
Thanks @krainboltgreene. I think discovering what the lowest versions of cycle/dom, cycle/run, and cycle/html where the bug happens, and the **highest** versions of cycle/dom|run|html where the bug does **not** happen.

**Comment by krainboltgreene** [comment] 2017-11-27 21:25
Will do when I get home.

**Comment by staltz** [comment] 2018-02-22 13:21
Any updates on this issue? I would like to solve it (and have some time for solving it) but I need to know first if it's a real issue in the framework.

**Comment by Tzelon** [comment] 2018-08-31 13:05
The issue is still relevant I create a repo to reproduce the problem 
https://github.com/Tzelon/cycle.js-ssr-bug

**Comment by jvanbruegge** [comment] 2018-09-02 17:42
@Tzelon You have to remove the `sinks.DOM = sinks.DOM.drop(1)`. It wont do anything to the DOM, but it will initialize the isolation scopes within cycle
Just commenting out this line and your repo works

**Comment by Tzelon** [comment] 2018-09-02 17:57
Thanks.
I thought the drop part should be there so we don't re-render the DOM.

**Comment by jvanbruegge** [comment] 2018-09-02 18:00
Snabbdom figures out that the dom did not change and does not rerender

**Comment by jvanbruegge** [comment] 2018-09-02 18:07
As I had no issues getting the excellent example of @Tzelon to work and the original repro segfaults, I will close this issue.
As far as I can tell is the original issue fixed with `@cycle/dom` v21

**Closed by jvanbruegge** 2018-09-02 18:07 UTC
Labels: issue is bug, priority 3 (should), scope: dom, scope: html

**Comment by Tzelon** [comment] 2018-09-03 07:10
Thanks, @jvanbruegge this solved my issue.
Can we update the isomorphic example? 
The client.js code from my repo copied from there https://github.com/cyclejs/cyclejs/blob/master/examples/advanced/isomorphic/client.js

**Comment by jvanbruegge** [comment] 2018-09-03 08:43
Yeah, I will update all examples in the next weeks (https://github.com/cyclejs/cyclejs/issues/802)
