### ISSUE TITLE
All errors in vdom hooks silently fail

### ISSUE THREAD

**Issue by mrapogee** [cyclejs/cyclejs#414] opened 2016-09-01 14:11 UTC
**Code to reproduce the issue:**
Run this component:

``` typescript
function main () {
  return {
    DOM: xs.of(div('.test', {hook: {insert: () => {throw new Error('error')}}}))
  }
}
```

**Expected behavior:**
It reports an error

**Actual behavior:**
It silently fails.
## This is because of the `rootElement$.addListener` line in makeDOMDriver that ignores all errors.

_Edited Oct 4 '16 at 21:38, @Frikki_
Corrected reproduction script `hooks` to `hook`.

**Comment by staltz** [comment] 2016-09-08 16:32
Yeah this seems like something we should handle. Thanks.

**Comment by kay-is** [comment] 2016-09-20 14:02
I looked into this, but I couldn't get it reproduced. Somehow the hook is nerver called.

Tried with:

    "@cycle/dom": "^12.2.5",
    "@cycle/xstream-run": "^3.1.0",
    "xstream": "^6.3.0"

**Comment by mrapogee** [comment] 2016-09-20 14:27
My bad, the code you should use is:

```
function main () {
  return {
    DOM: xs.of(div('.test', {hook: {insert: () => {throw new Error('error')}}}))
  }
}
```

Note `hooks:` is actually `hook`

**Comment by mrapogee** [comment] 2016-09-20 15:18
Here is a [reproduction code pen](http://codepen.io/mrapogee/pen/qaqkGx?editors=0010).

**Comment by kay-is** [comment] 2016-09-20 16:59
Hm, I tried to re-throw the error, but then it gets swallowed by another stream, that has no listeners (https://github.com/staltz/xstream/blob/master/src/core.ts#L1143)

I don't know if this is expected behavior of xstream/cycle (i.e. swallowing all errors unless you get the right stream and put a listener or debug-listener on it) or if xstream should also throw unhandled errors.

**Comment by mrapogee** [comment] 2016-09-20 17:58
Could something like this [pen](http://codepen.io/mrapogee/pen/gwLLaZ/?editors=0010) be happening?

The above is the only way I can find to trigger an error when a stream has no listeners. The stream completes after 3 seconds, but the producer doesn't stop triggering events. After five seconds, it triggers an error via `listener.error`, and the error silently fails.

xstream should probably check if the listener has 0 listeners and throw the error directly if it doesn't. I'll report this upstream if this is what is happening.

**Comment by kay-is** [comment] 2016-09-20 18:46
Yes seems to be.

https://github.com/staltz/xstream/issues/121

**Comment by staltz** [comment] 2017-01-19 22:06
Fixed in the `unified` branch. Not yet released.

**Closed by staltz** 2017-01-19 22:06 UTC
Labels: help wanted, issue is bug, priority 3 (should), scope: dom, size S
