### ISSUE TITLE
Strange behaviour when using xs.combine array in hyperscript helper

### ISSUE THREAD

**Issue by Steelfish** [cyclejs/cyclejs#537] opened 2017-03-03 11:32 UTC
Using xstream 10.2.0 and @cycle/dom 15.2.0 I've encountered the following mind boggling behaviour.
When given an array of VNode's produced by an xs.combine stream, the DOM is not updated when the array changes. The same array produced by a .map(node => [node]) however does update the DOM! And the output of both for as far as I can see, is identical! It seems to be an issue with cycle/DOM. In version 14.3.0 the same code does update the DOM.

**Code to reproduce the issue:**
```javascript
let testApp = function (sources) {
  let vTree$:any = xs.periodic(2000).map(t => (t % 2) === 0 ? div({
    props: { className: "Class 1" },
    style: { width: "20px", height: "20px", backgroundColor: "#FF0000" }
  }) : div({
    props: { className: "Class 2" },
    style: { width: "20px", height: "20px", backgroundColor: "#00FF00" }
  }));

  // vTree$ = vTree$.map(v => [v]); // DOES update the DOM.
  vTree$ = xs.combine(vTree$); // DOES NOT update the DOM
  return {
    DOM: vTree$.map(n => div(n))
  };
};
run(testApp, {
  DOM: makeDOMDriver("#app")
});
```

**Expected behavior:**
The DOM should update when given an array of VNode's produced by xstream's combine.

**Actual behavior:**
The DOM does not update.

**Versions of packages used:**
"@cycle/dom": "^15.2.0",
"@cycle/run": "^1.0.0",
"xstream": "^10.2.0"

**Comment by staltz** [comment] 2017-03-03 11:48
I think it's because you're mutating `vTree$` which should be a `const` by the way. This code below worked:

```js
import xs from 'xstream'
import {run} from '@cycle/run'
import {makeDOMDriver, div} from '@cycle/dom'

let testApp = function (sources) {
  let vTree$ = xs.periodic(1000).map(t => (t % 2) === 0 ? div({
    props: { className: "Class 1" },
    style: { width: "20px", height: "20px", backgroundColor: "#FF0000" }
  }) : div({
    props: { className: "Class 2" },
    style: { width: "20px", height: "20px", backgroundColor: "#00FF00" }
  }))

  // Before
  //const vdom$ = vTree$.map(v => [v]).map(n => div(n))
  
  // After
  const vdom$ = xs.combine(vTree$).map(n => div(n))

  return {
    DOM: vdom$
  };
};
run(testApp, {
  DOM: makeDOMDriver("#app")
});
```

That said, `xs.combine` is tricky because it **mutates** the output array instead of emitting new array references every time. This behavior means major performance improvements when compared to emitting new arrays, but in some cases you need to be careful that this mutation doesn't cause bugs.

**Comment by Steelfish** [comment] 2017-03-03 11:54
I am still not seeing any changes running your code on Chrome Version 56.0.2924.87

**Comment by staltz** [comment] 2017-03-03 11:57
Right, I was using Cycle DOM v14 (because ESNext bin chose that automatically) and indeed with v15 the bug occurs.

**Comment by Steelfish** [comment] 2017-03-03 11:59
Using lodash's clone version to clone the output from xstream's combine array does work to trigger DOM updates. So this has to be related to the mutated array output, I think.

**Comment by staltz** [comment] 2017-03-03 12:02
It's strange, though, because in both working and nonworking examples, xstream version is v10.2 with the mutating combine output.

**Comment by Steelfish** [comment] 2017-03-03 12:04
I agree, it's a very mind boggling issue! Certainly some kind of regression must have happened between 14.3.0 > 15.2.0 to stop the mutated array from working. I am still looking if I can find the root of the problem.

**Comment by TylorS** [comment] 2017-03-03 12:05
Transposition may have created copies of the array before?

**Comment by staltz** [comment] 2017-03-03 12:05
Right now my strongest assumption is that it's a combination of xstream combine's mutating behavior plus snabbdom's reference equality checks on vdom children (which changed a bit from Cycle DOM 14 to 15).

**Comment by staltz** [comment] 2017-03-03 12:06
> Transposition may have created copies of the array before?

Tylor :+1: so smart

**Comment by staltz** [comment] 2017-03-03 12:07
Anyway, by now it's obvious this is a bug and not just a question.

**Comment by TylorS** [comment] 2017-03-03 12:15
> Right now my strongest assumption is that it's a combination of xstream combine's mutating behavior plus snabbdom's reference equality checks on vdom children

This makes a lot of sense, too.

**Comment by Steelfish** [comment] 2017-03-03 13:35
I did some debugging and for as far as I can tell, the DOM is not being updated because of this line: 

https://github.com/snabbdom/snabbdom/blob/master/src/snabbdom.ts#L267

where snabbdom checks if the children are equal. I believe this is because of the referenced array that xs.combine produces.

I can definitely see why such a check might be prudent. Would mutated array references be common enough to merit the test's removal or should this problem be solved in cycle/dom?

**Comment by staltz** [comment] 2017-03-03 13:45
Basically yeah, but the issue is deeper. The problem is that at some point in the patch, both vnode and oldVNode refer to the same object because the oldVNode's content was mutated. So a patch on that will do nothing.

**Comment by Steelfish** [comment] 2017-03-03 13:50
Should vnodes copy children array references? I can imagine that everything becomes a lot easier if vnodes produce immutable children arrays. Although I guess this comes with a performance impact.

**Comment by staltz** [comment] 2017-03-03 13:56
That would have to be done in snabbdom and I don't think it's the correct spot because snabbdom's optimization by reference is actually a good idea. Currently I think the candidate solutions are:

- In general use combine+map in a way that will create a new array, e.g. notice this https://github.com/cyclejs/cyclejs/blob/master/examples/bmi-nested/src/BmiCalculator.js#L16
- Or use `combine(a$,b$).map(n => div([...n]))`
- Clone the array in xstream (would have performance drawback everywhere)

**Comment by staltz** [comment] 2017-03-03 14:03
I'm confused, however, why does this work https://github.com/staltz/cycle-onionify/blob/07d1199432ca5d676ec4ab433c628f9a8a349f17/examples/advanced/src/List.ts#L29-L32

**Comment by Steelfish** [comment] 2017-03-03 14:04
I definitely think the best solution is to place the performance penalty on the consumer of xstream's combine and snabbdom. As long as you are aware of the way that these optimizations conflict with eachother, you can work around them by cloning the array yourself. The only problem I see is how to make this interaction apparant.

**Comment by Steelfish** [comment] 2017-03-03 14:04
https://github.com/staltz/cycle-onionify/blob/07d1199432ca5d676ec4ab433c628f9a8a349f17/examples/advanced/package.json

Old @cycle/dom?

**Comment by Steelfish** [comment] 2017-03-03 14:10
Another possibility is to add array cloning in cycle/dom's hyperscript helpers.

**Comment by staltz** [comment] 2017-03-03 14:29
Sorry I had the wrong link, this one uses DOM v15 and also works https://github.com/staltz/cycle-onionify/blob/ff461f788362c6801538aa1e4efc345cd53c4c1c/examples/advanced/package.json

**Comment by staltz** [comment] 2017-03-03 14:34
> Another possibility is to add array cloning in cycle/dom's hyperscript helpers.

True, it could be this:

```diff
function createTagFunction(tagName: string): Function {
  return function hyperscript(a: any, b?: any, c?: any): VNode {
    const hasA = typeof a !== 'undefined';
    const hasB = typeof b !== 'undefined';
    const hasC = typeof c !== 'undefined';
+   if (Array.isArray(a)) a = a.slice();
+   if (Array.isArray(b)) b = b.slice();
+   if (Array.isArray(c)) c = c.slice();
    if (isSelector(a)) {
      if (hasB && hasC) {
        return h(tagName + a, b, c);
      } else if (hasB) {
        return h(tagName + a, b);
      } else {
        return h(tagName + a, {});
      }
    } else if (hasC) {
      return h(tagName + a, b, c);
    } else if (hasB) {
      return h(tagName, a, b);
    } else if (hasA) {
      return h(tagName, a);
    } else {
      return h(tagName, {});
    }
  };
}
```

**Comment by TylorS** [comment] 2017-03-03 14:41
https://github.com/staltz/cycle-onionify/blob/master/examples/advanced/src/List.ts#L31

This still works because `xs.combine` is being called on every stream emission, so a new array is created each time.

**Comment by staltz** [comment] 2017-03-03 14:42
Right!

PS: right now I'm experimenting with which cloning strategy is the fastest (https://jsperf.com/new-array-vs-splice-vs-slice/19) and if the perf hit isn't bad on xstream, I'll do cloning in xstream. Or in hyperscript helper.

**Comment by TylorS** [comment] 2017-03-03 14:52
You should also try adding a test like
```
b = Array(a.length)

for (var i = 0; i < a.length; ++i)
  b[i] = a[i]
```

**Comment by staltz** [comment] 2017-03-03 15:18
Current xstream version:

```
combine(add3) -> filter 500000 x 3 integers
-----------------------------------------------
xstream      19.47 op/s ±  1.54%   (49 samples)
most         48.26 op/s ±  1.29%   (73 samples)
rx 5         11.59 op/s ±  1.46%   (56 samples)
-----------------------------------------------
```

When using cloning of the type `while (i--) b[i] = a[i]` in xstream combine:

```
combine(add3) -> filter 500000 x 3 integers
-----------------------------------------------
xstream      12.29 op/s ±  4.66%   (60 samples)
most         48.92 op/s ±  0.90%   (73 samples)
rx 5         10.96 op/s ±  2.49%   (53 samples)
-----------------------------------------------
```

I'd say these results are satisfactory, given that it's still a bit faster than RxJS.

**Comment by staltz** [comment] 2017-03-03 15:28
@TylorS Yep you're suggestion of yields

```
combine(add3) -> filter 500000 x 3 integers
-----------------------------------------------
xstream      16.10 op/s ±  1.18%   (73 samples)
most         48.62 op/s ±  0.90%   (73 samples)
rx 5         11.28 op/s ±  1.20%   (55 samples)
-----------------------------------------------
```

Which is awesome. Let's do this fix in xstream so we solve this for good.

**Comment by staltz** [comment] 2017-03-03 15:29
Closing this issue because it's in xstream instead. Keep an eye on upcoming xstream v10.3

**Closed by staltz** 2017-03-03 15:29 UTC
Labels: issue is bug, priority 4 (must), resolution: invalid, scope: dom

**Comment by staltz** [comment] 2017-03-04 12:39
@Steelfish did xstream v10.3 fix it for you?

**Comment by Steelfish** [comment] 2017-03-04 12:52
@staltz Using xstream v10.3 I am indeed seeing the expected behaviour.
