### ISSUE TITLE
(DOM) Svg pattern fill not displayed

### ISSUE THREAD

**Issue by sveinburne** [cyclejs/cyclejs#461] opened 2016-10-16 21:32 UTC
**Code to reproduce the issue:**
- The full minimal working example is available at this github repo : [https://github.com/sveinburne/cyclejs-svg-bug](https://github.com/sveinburne/cyclejs-svg-bug).
- The non-working component is [Circle.js](https://github.com/sveinburne/cyclejs-svg-bug/blob/master/app/Circle.js).

**Expected behavior:**
![svg-circle-expected](https://cloud.githubusercontent.com/assets/3646758/19421026/7e96f266-93c5-11e6-8a08-12308b29c308.png)

The background pattern defined in `svg.pattern` function should be rendered in the real DOM.

[You can open this file in a browser to watch the expected rendering](https://raw.githubusercontent.com/sveinburne/cyclejs-svg-bug/master/working-svg.html).

**Actual behavior:**

![svg-circle-issue](https://cloud.githubusercontent.com/assets/3646758/19421017/50ecd682-93c5-11e6-910c-999264b48c7b.png)

In the browsers I could test (chromium, firefox), the circle is normally displayed, but the `fill` background is missing.
In the DOM, I cannot however see any difference between [the expected rendering](https://raw.githubusercontent.com/sveinburne/cyclejs-svg-bug/master/working-svg.html) and the actual rendering. 

**Versions of packages used:**

@cycle/dom : 13.0.0 (same issue in 12.X)
[Check the full package.json](https://raw.githubusercontent.com/sveinburne/cyclejs-svg-bug/master/package.json)

**Comment by TylorS** [comment] 2016-10-16 23:24
I can confirm this is a bug. I've recreated this [here](https://esnextb.in/?gist=ee2c3285fbeb56d8232e28ee18495831). It's possible to workaround this issue by using innerHTML as shown in the link.

**Comment by TylorS** [comment] 2016-10-16 23:25
There is a high probability this is a snabbdom bug, but I haven't been able to rule out this being an issue with the locally defined versions of h() and hyperscript helper functions.

**Comment by laszlokorte** [comment] 2016-10-17 10:36
I am pretty sure that is a chrome/webkit bug.

Modifying `<use>` or `<image>` elements via js (I guess everything with xlink:href) causes the element to not disappear. You can try it by using dev tools to edit the `x` attribute of your (@TylorS) working example. The image disappears instantly.

https://bugs.webkit.org/show_bug.cgi?id=74392

I spent a whole day last week debugging such an issue in a react application. The issue I linked is marked as closed but when googling you will find other thread (eg on SO) where people still have the problem. In my specific case the problem could be worked around by increasing the cache period for the svg files but in this case it seems not to help.

**Comment by sveinburne** [comment] 2016-10-17 15:10
@laszlokorte I could reproduce in firefox (49.0) and chromium (53.0)...

**Comment by mkaemmerer** [comment] 2016-10-17 15:14
This is a Snabbdom issue: https://github.com/snabbdom/snabbdom/blob/master/modules/attributes.js#L26

The problem is that the attribute "xlink:href" must be set using setAttributeNS. Setting it with setAttribute does not work.
```
//Wrong
element.setAttribute('xlink:href', url);
// Right
element.setAttributeNS('http://www.w3.org/1999/xlink', 'xlink:href', url);
```

**Comment by mkaemmerer** [comment] 2016-10-17 15:25
That being said, apparently the "xlink:href" attribute is now [deprecated](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href). Using "href" with no namespace prefix works fine.

**Comment by sveinburne** [comment] 2016-10-17 16:15
@mkaemmerer Great, I think you've pinned the snabbdom bug! Will you push a PR or shall I ?

I had no success in firefox with the `href` attribute, even when I added a `version` attribute ` ="2.0"` at `svg` root element.

**Comment by mkaemmerer** [comment] 2016-10-17 16:22
@sveinburne yep I'm working on a PR for it!
Thanks for double-checking the href attribute. I only checked Chrome, but it seemed to work there.

**Comment by sveinburne** [comment] 2016-11-20 18:01
@mkaemmerer thanks a lot, it does work when I force `snabbdom` dependency to `0.5.4` in `@cycle/dom`. 
However, I wanted to push a PR but the tests didn't pass when I changed dependency... and I don't have the time / insight to investigate further ... anyone ?

**Comment by staltz** [comment] 2017-01-20 09:08
This was a bug in snabbdom which is now fixed thanks to the PR resulting from this discussion. snabbdom was updated in Cycle DOM in the `unified` branch and we'll close this issue, release the version later.

**Closed** 2017-03-06 09:50 UTC
Labels: priority 3 (should), resolution: fixed, scope: dom
