### ISSUE TITLE
Isolate: Implicit scope in nested component causes streams to be ignored/gobbled

### ISSUE THREAD

**Issue by wyqydsyq** [cyclejs/cyclejs#370] opened 2016-07-27 04:37 UTC
It's probably just me doing something wrong, but if you take a look at:
https://github.com/wyqydsyq/hapi-cycle/blob/master/src/ui/components/create-user/index.js

You can see I'm exporting the component self-isolated. When I provide a scope string it works fine, however if I try to use an implicit scope by not specifying the scope string, all of my intent/`actions` streams stop emitting except for those merged in `model()` and used for building the DOM sink.

You can see this in action if you `git clone` + `npm install` + `npm run launch` a HapiCycle app based on https://github.com/wyqydsyq/hapi-cycle/commit/d09c85938ab8c225133c12e4b3ea5001aa751f6e, the create-user component will work fine with the explicit scope string, but if you make it implicit suddently streams in that component only emit events if they're used in the context of building the DOM sink. Most noticeably the HTTP sink stops emitting POST requests because the `actions.submit$` it's listening to won't emit anything, even though the exact same stream emits just fine in the context of `model()`/`state$`, presumably because it affects the DOM sink's VTree (via altering `state` in `model()`) in that case.

I'm guessing I've set it up incorrectly in a way that's causing the component to get a new generated scope each time it's rendered or something, but really have no idea. Any advice would be appreciated. Thanks.

**Comment by staltz** [comment] 2016-07-29 08:45
Right now I don't have time to investigate this, but if a small reproducible case pops up, maybe I can look at it. I'm not sure to label this issue a bug or question-like discussion.

**Comment by Hypnosphi** [comment] 2016-07-29 23:28
Is there a chance that cycle router calls your `WelcomePage` more than once? Can you maybe track this with devTools debugger?

**Comment by wyqydsyq** [comment] 2016-08-03 04:03
@Hypnosphi I investigated deeper and can confirm you're correct; this seems to be an issue with `cyclic-router` rather than `@cycle/isolate`. When using the router the `WelcomePage` gets called twice, and any isolated child components of `WelcomePage` seem to lose track of their namespace/scope when it's called the second time. If I don't isolate my child components, isolate them with explicit scopes, or if I just call `WelcomePage` directly instead of via `cyclic-router` it works perfectly.

I've opened a new issue for this at https://github.com/cyclejs-community/cyclic-router/issues/95, probably best to close this current one.

**Comment by ntilwalli** [comment] 2016-08-03 16:04
Your route stream is not being multicast and it needs to be.  I commented in the other issue: 
https://github.com/cyclejs-community/cyclic-router/issues/95

**Comment by ShayMatasaro** [comment] 2016-08-04 10:23
@ntilwalli xstream should handle multicast natively without the need for remember()
this looks like similar issue to the one i reported in : 
https://github.com/staltz/xstream/issues/96
where i see both:
- streams getting executed more then once
- events getting lost along the way

**Comment by ntilwalli** [comment] 2016-08-04 20:32
@ShayMatasaro yeah, I initially forgot about the default multicasting in xstream, but I remembered and commented on the referenced cyclic-router issue to that effect. This seems like a xstream bug of some sort.

**Comment by schirinos** [comment] 2016-08-19 20:24
I have this exact same issue and can confirm what @wyqydsyq mentioned.

Here is a snippet of the affected code:
https://gist.github.com/schirinos/8d56f38580b9536cdf979c357a48a9c9

It seems that it might be an xstream bug. Not sure if it is bug in xtstream or isolate. Oddly, adding a ``debug`` or ``remember`` to the stream that creates the component seems to fix it.  ``debug`` or ``remember`` are changing the stream in some way to alleviate an isolate bug perhaps.

**Comment by staltz** [comment] 2016-08-30 20:34
There's so much going on here, it's hard to know where the problem is. Some people mentioned it could be in xstream (which version?), some mentioned cyclic-router, and isolate.

So help me out, someone?
- Small reproducible case
- What's the expected output?
- What's the actual output?
- What are the versions of packages used?

I don't have time to dwell over each issue, so keeping it simple and fact-based will help me to help you quicker.

**Comment by wyqydsyq** [comment] 2016-08-31 00:59
I believe this may actually have been a case of https://github.com/staltz/xstream/issues/91, I've updated my project to use xstream `6.2.0` and it doesn't seem to occur any more.

**Comment by staltz** [comment] 2016-10-14 10:48
Ok, let's close this issue. If something similar happens again, we open a new issue, or reopen this.

**Closed by staltz** 2016-10-14 10:48 UTC
Labels: labels pending!
