### ISSUE TITLE
`remove` animation on components breaks DOM isolation

### ISSUE THREAD

**Issue by atomrc** [cyclejs/cyclejs#747] opened 2017-11-17 14:57 UTC
**Code to reproduce the issue:** 

Live demo : https://www.webpackbin.com/bins/-Kz9T7jtEIMlufYbmkyY

```javascript
import { run } from "@cycle/run";
import { makeDOMDriver, div, button } from "@cycle/dom";
import isolate from "@cycle/isolate";
import onionify, { makeCollection } from "cycle-onionify";
import xs from "xstream";

function Child(sources) {
  const remove$ = sources.DOM.select(".click")
    .events("click")
    .mapTo(state => ({ show: false }))
  
  const style = {
    transition: "transform 1s",
    /** the remove handler seems to break isolation **/
    remove: {
      transform: "translateY(100%)"
    }
    /** END **/
  }
  
  return {
    DOM: xs.of(button(".click", { style: style }, "remove")),
    onion: remove$
  }
}

function main(sources) {
  
  const initialReducer$ =  xs.of(() => ({ show: true }));
  
  const child = isolate(Child, { onion: null })(sources);
  
  const showChild$ = sources.DOM.select(".click")
    .events("click")
    .mapTo(state => ({ show: true }))
  
  return {
    DOM: xs.combine(sources.onion.state$, child.DOM)
      .map(([state, child]) => div(
        [button(".click", "show"), (state.show ? child: null)])
      ),
    onion: xs.merge(initialReducer$, showChild$, child.onion)
  }
}

run(onionify(main), {
  DOM: makeDOMDriver("#main")
});
```

**Expected behavior:**
The remove button, when clicked, should disappear and only the `show` button should be visible.

**Actual behavior:**
The remove button, when clicked, disappears but another remove button is also added

**Versions of packages used:**
    cycle/dom    20.1.0
    cycle/isolate   3.2.0
    cycle/run    4.0.0
    cycle-onionify    4.0.0

**Comment by staltz** [comment] 2017-11-27 11:10
Hi @atomrc  :)
Thanks for letting us know about this. Yes, it seems related to isolation. When used like `isolate(Child, {onion: null})`, it means there is a randomly generated isolation scope given to the DOM channel.

I'm investigating what is the root cause of this, but for now, notice that if you wrap the child's button:

```js
DOM: xs.of(div([button('.click', {style:style}, 'remove')])),
```

Then the issue goes away. So it seems like a logic bug in the DOM isolation layers **OR** an issue with documentation or intended usage of this API. I'll investigate.

**Comment by staltz** [comment] 2017-11-27 11:28
What I've found so far: (1) it's a race condition, (2) it's related to ScopeChecker.

(1) depending how fast I step through the debugger, this bug doesn't occur. That's because this bug only occurs if the element is still present. This seems to happen because snabbdom retains the element until the animation ends: https://github.com/snabbdom/snabbdom/blob/2271b7bdf15577eabd8de961f4e5bba5bd1515fe/src/modules/style.ts#L63

(2) This bug occurs when ScopeChecker.isDirectlyInScope runs through all iterations, and finally returns with default `true`. In other words, the ScopeChecker thinks that the animating element is in the root scope. Maybe the solution is reimplementing our own snabbdom module for styles, which retains also the EventDelegators and Isolation state until the animation ends.

- - -

> I'm investigating what is the root cause of this, but for now, notice that if you wrap the child's button:
> ```js
> DOM: xs.of(div([button('.click', {style:style}, 'remove')])),
>
> Then the issue goes away. So it seems like a logic bug in the DOM isolation layers OR an issue with documentation or intended usage of this API. I'll investigate.

Actually this was wrong because the button wouldn't even animate if there is a wrapping div.

**Comment by atomrc** [comment] 2017-12-08 21:44
Hi @staltz, thanks for you reply : )

Indeed it seems to be a race condition. 
I have been investigating this issue lately.
I am not yet at the bottom of it (I still don't really understand why a second non-scoped `click` event is fired), but it seem if I wrap the `post` hook of the isolation module of the DOM driver, the issue vanishes.

```javascript
            post: function () {
                setTimeout(() => {
                    var vnodesBeingRemoved = self.vnodesBeingRemoved;
                    for (var i = vnodesBeingRemoved.length - 1; i >= 0; i--) {
                        self.cleanupVNode(vnodesBeingRemoved[i]);
                    }
                    self.vnodesBeingRemoved = [];
                    self.fullScopesBeingUpdated = [];
                });
            },
```

Do you think it is a reasonable thing to do to delay the cleaning of vnodes when the main thread is idle?
Or is it too much of a change and it could generate breaking changes? (I bet, at least, some tests will need to be fixed ...).

**Comment by staltz** [comment] 2017-12-20 11:31
Hey @atomrc, that could work, but I'd like to try reimplementing the snabbdom module for styles, with event delegators and isolation in mind. Might be a good thing to do this around the same time we are doing #751 and #759.

**Comment by jvanbruegge** [comment] 2018-08-25 08:56
I found a fix for this: https://github.com/snabbdom/snabbdom/pull/390
Waiting on the merge and on bumping the dependency

**Closed** 2018-09-04 09:27 UTC
Labels: issue is bug, priority 3 (should), scope: dom, scope: isolate
